app.loader.type=Random
app.loader.path=src/main/resources/map_lvl.txt
app.loader.tanks=3
app.loader.rows=5
app.loader.columns=5
app.tank.player.path=images/tank_blue.png
app.tank.path=images/tank_red.png
app.tree.path=images/greenTree.png
app.bullet.path=images/bullet.png
app.level.path=level.tmx